# Generated by Django 4.0.3 on 2022-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boyi', models.CharField(max_length=10)),
                ('eni', models.CharField(max_length=10)),
                ('qoshimcha', models.TextField()),
                ('tel_raqam', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Haridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('tel_raqam', models.CharField(max_length=13)),
                ('buyurtma', models.TextField()),
            ],
        ),
    ]
