# Generated by Django 4.0.3 on 2022-04-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='fi',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
